name: Next.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.20.2'
    - name: Install dependencies
      run: npm install
      working-directory: ./nextjs-app
    - name: Lint
      run: npm run lint
      working-directory: ./nextjs-app
    - name: Test
      run: npm run test --passWithNoTests
      working-directory: ./nextjs-app
